"""
Format the per-role keyword CSVs into docs/role-skill-evidence.md.

Usage:
  python scripts/jobs/report.py
  python scripts/jobs/report.py --top 30

Reads data/jobs/<role>-keywords.csv (produced by extract.py) and writes a
single markdown report grouping the top-N keywords per role with their
percent-of-postings frequency. Uses today's date in the report header so the
file shows when the underlying job-listing pull was taken.

The report is meant to be eyeballed for "which keyword shows up most often in
each role's postings, and how does that compare to LearnCRE's content
emphasis." Big asymmetries (Argus 70% in acquisitions but missing from our
content) are signals to add new content.
"""

from __future__ import annotations

import argparse
import csv
import sys
from datetime import date
from pathlib import Path

from keywords import ROLE_QUERIES

DATA_DIR = Path(__file__).resolve().parents[2] / "data" / "jobs"
OUT_PATH = Path(__file__).resolve().parents[2] / "docs" / "role-skill-evidence.md"

ROLE_LABELS: dict[str, str] = {
    "acquisitions": "Acquisitions",
    "assetManagement": "Asset Management",
    "mortgageUw": "Mortgage Underwriting",
    "portfolioMgmt": "Portfolio Management",
    "development": "Development",
}


def load_role(role: str) -> tuple[list[dict[str, str]], int]:
    """Returns (rows, postings_count). postings_count from the highest-ranked row's
    mentions/% ratio, or 0 if no rows."""
    p = DATA_DIR / f"{role}-keywords.csv"
    if not p.exists():
        return [], 0
    rows: list[dict[str, str]] = []
    with p.open() as f:
        for r in csv.DictReader(f):
            rows.append(r)
    if not rows:
        return [], 0
    # Postings count = postings_count + mentions ratios; use the row with the
    # most postings as authoritative.
    try:
        max_postings = max(int(r["postings_count"]) for r in rows)
    except (KeyError, ValueError):
        max_postings = 0
    return rows, max_postings


def role_section(role: str, top_n: int) -> str:
    rows, n_postings = load_role(role)
    label = ROLE_LABELS[role]
    if not rows:
        return (
            f"### {label}\n\n"
            f"_No data — run `python scripts/jobs/fetch.py --role {role}` then "
            f"`python scripts/jobs/extract.py --role {role}`._\n"
        )
    # Filter zero-mention keywords from the head of the list since they're noise
    nonzero = [r for r in rows if int(r["postings_count"]) > 0]
    head = nonzero[:top_n]

    lines: list[str] = []
    lines.append(f"### {label}")
    lines.append("")
    lines.append(f"Sample: **{n_postings}** postings (deduplicated).")
    lines.append("")
    lines.append("| Keyword | % of postings | Mentions | Postings |")
    lines.append("|---|---:|---:|---:|")
    for r in head:
        kw = r["keyword"]
        pct = r["percent_of_postings"]
        m = r["mentions"]
        p = r["postings_count"]
        lines.append(f"| `{kw}` | {pct}% | {m} | {p} |")
    return "\n".join(lines) + "\n"


def render(top_n: int = 30) -> str:
    today = date.today().isoformat()
    parts: list[str] = []
    parts.append("# LearnCRE — role / skill evidence (auto-generated)")
    parts.append("")
    parts.append(
        "Skill-keyword frequency across recent CRE job postings, by role. "
        "Generated by `scripts/jobs/report.py` from CSVs in `data/jobs/`. "
        "Re-run quarterly; bigger asymmetries between this report and our "
        "content emphasis are signals for new content."
    )
    parts.append("")
    parts.append(f"**Last refresh:** {today}")
    parts.append("")
    parts.append(
        "**How to read.** `% of postings` is the share of postings in that "
        "role that mention the keyword at least once. `Mentions` is the raw "
        "count across all postings (so a keyword in every paragraph of one "
        "posting can show high mentions but low postings %, and is less "
        "indicative). Trust the percent column."
    )
    parts.append("")
    parts.append("---")
    parts.append("")
    for role in ROLE_QUERIES.keys():
        parts.append(role_section(role, top_n))
        parts.append("")
    parts.append("---")
    parts.append("")
    parts.append("## How to read against LearnCRE content")
    parts.append("")
    parts.append(
        "Look for high-percent keywords that aren't already drilled in our "
        "content. Examples of patterns to watch for:"
    )
    parts.append("")
    parts.append(
        "- A tool that's in 70%+ of postings but missing from our content "
        "(e.g. `Argus` in acquisitions, `vba` in asset mgmt) → consider an "
        "Excel template or a situational case that exercises that tool's "
        "framing."
    )
    parts.append(
        "- A metric that's in 50%+ of one role's postings but <10% of "
        "another's (e.g. `debt yield` mortgage UW vs portfolio mgmt) → "
        "validates the role tag on existing content."
    )
    parts.append(
        "- A keyword we treat as universal that postings split sharply on "
        "(e.g. `lp` / `gp` showing up only in portfolio mgmt) → tighten "
        "the role tag on situational cases that mention it."
    )
    parts.append("")
    return "\n".join(parts)


def main() -> int:
    parser = argparse.ArgumentParser(description="Render skill-evidence markdown")
    parser.add_argument(
        "--top", type=int, default=30, help="Top N keywords per role (default 30)"
    )
    args = parser.parse_args()

    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text(render(args.top))
    print(f"wrote {OUT_PATH}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
