/**
 * Lightweight index of catalog ids and categories, so code that only needs
 * to *count* or *categorize* content (achievements, sync, profile) doesn't
 * pull the full case/test libraries into the app shell bundle.
 * `src/test/catalogIndex.test.ts` fails if this drifts from the catalog.
 */
import type { SituationalCategory } from '../types/situational';

export const SITUATIONAL_CATEGORY_BY_ID: Record<string, SituationalCategory> = {
  'cap-rate-divergence': 'pricing',
  'absorption-timing': 'absorption',
  'mark-to-market-upside': 'pricing',
  'noi-growth-smell-test': 'diagnostic',
  'comp-set-vetting': 'comp-selection',
  'tax-reassessment-surprise': 'risk',
  'rent-roll-undervalued': 'pricing',
  'ti-vs-rent-giveback': 'lease-econ',
  'refi-vs-sell': 'investment-thesis',
  'going-in-vs-exit-cap-spread': 'sensitivity',
  'vacancy-spike': 'diagnostic',
  'tenant-credit-pricing': 'pricing',
  'dscr-refi-failing': 'risk',
  'comp-vintage-adjustment': 'comp-selection',
  'exit-cap-conservatism': 'sensitivity',
  'trended-vs-inplace-leaseup': 'pricing',
  'noi-growth-missing': 'diagnostic',
  'rollover-concentration': 'risk',
  'sponsor-proforma-aggressive': 'diagnostic',
  'debt-yield-vs-dscr': 'risk',
  'over-weight-office': 'investment-thesis',
  'hold-extension-discipline': 'investment-thesis',
  'tax-vs-irr-tradeoff': 'investment-thesis',
  'capex-reserve-discipline': 'diagnostic',
  'refi-cap-stress': 'risk',
  'fund-vs-deal-irr-gap': 'diagnostic',
  'dev-ltc-vs-ltv': 'risk',
  'distressed-loan-workout': 'investment-thesis',
  'lease-structure-nnn-vs-gross': 'lease-econ',
  'sponsor-recourse-vs-covenants': 'risk',
  'ground-lease-vs-fee': 'investment-thesis',
  'capital-call-mechanics': 'deal-process',
  'closing-prorations': 'deal-process',
  'construction-cost-overrun': 'deal-process',
  'lender-draw-mechanics': 'deal-process',
  'bank-account-structure': 'deal-process',
  'balance-sheet-refi-impact': 'deal-process',
  'budget-vs-actual-variance': 'deal-process',
  'distribution-waterfall-1tier': 'deal-process',
  'closing-checklist-sequence': 'deal-process',
  'covenant-testing-cadence': 'deal-process',
  'cost-segregation-basics': 'deal-process',
  'om-red-flags': 'pricing',
  'tenant-improvement-approval': 'deal-process',
  'waterfall-european-vs-american': 'deal-process',
  'waterfall-catchup-mechanics': 'deal-process',
  'waterfall-irr-vs-moic-hurdle': 'deal-process',
  'waterfall-clawback-mechanics': 'deal-process',
  'waterfall-pref-compound-vs-simple': 'deal-process',
  'waterfall-key-person-event': 'deal-process',
  'dscr-test-timing-mechanics': 'document-literacy',
  'dscr-cash-trap-trigger': 'document-literacy',
  'dscr-cure-rights': 'document-literacy',
  'dscr-springing-recourse': 'document-literacy',
  'lpa-initial-vs-additional-capital': 'document-literacy',
  'lpa-capital-call-default': 'document-literacy',
  'lpa-cost-overrun-sharing': 'document-literacy',
  'lpa-contribution-ratios': 'document-literacy',
  'lease-billback-allowance': 'document-literacy',
  'lease-base-year-vs-stop': 'document-literacy',
  'lease-cam-reconciliation': 'document-literacy',
  'construction-liquidated-damages': 'document-literacy',
  'psa-earnest-money-default': 'document-literacy',
  'construction-equity-first-vs-paripassu': 'deal-process',
  'construction-change-order-pricing': 'deal-process',
  'construction-retainage-release-trigger': 'deal-process',
  'capital-allocation-priority': 'investment-thesis',
  'risk-adjusted-return-framework': 'investment-thesis',
  'hotel-revpar-divergence': 'diagnostic',
  'retail-percentage-rent-clause': 'investment-thesis',
  'industrial-truck-court-bid': 'pricing',
};

export const WALKTHROUGH_IDS: readonly string[] = [
  'walk-combined-1',
  'walk-dscr-1',
  'walk-acq-mock-1',
  'walk-am-valueadd-1',
  'walk-dev-feasibility-1',
  'walk-am-holdsell-1',
  'walk-distressed-1',
  'walk-waterfall-1',
  'walk-construction-draw-1',
  'walk-hotel-revpar-1',
  'walk-office-walt-1',
];

export const MODELING_TEST_IDS: readonly string[] = [
  'dcf-5yr-suburban-office',
  'loan-sizing-three-constraint',
  'acq-proforma-multifamily',
  'refi-vs-sell-y5',
  'construction-loan-sizing-midrise',
  'distressed-office-basis-play',
];
