// Bundles the shared, pure scoring code (src/server/*) into a single ESM file
// the Supabase Edge Function can import, so the server grades with exactly
// the same generators + tolerance rules the browser uses.
//
//   npm run build:edge
//
// The output is committed; CI rebuilds it and fails if it is stale.
import { build } from 'esbuild';

await build({
  entryPoints: ['src/server/scoreChallengeHandler.ts'],
  outfile: 'supabase/functions/_shared/scoring.bundle.js',
  bundle: true,
  format: 'esm',
  platform: 'neutral',
  target: 'es2022',
  legalComments: 'none',
  logLevel: 'warning',
  banner: {
    js: '// @ts-nocheck\n// GENERATED by scripts/build-edge.mjs from src/server/ — do not edit.\n// Run `npm run build:edge` after changing question generators or scoring.',
  },
});
console.log('wrote supabase/functions/_shared/scoring.bundle.js');
